#!/bin/sh
ECHO=`which echo`
BUILDDIR="/opt/hachdev/buildsystem/r2009/build"
FIRST_TIME=0
cd /opt/hachdev/buildsystem/r2009/sources/poky
if [ ! -f ${BUILDDIR}/conf/local.conf ]; then
	FIRST_TIME=1
fi

. ./oe-init-build-env ${BUILDDIR}

echo ""
echo "HACH provides the following image recipes for open source purpose."
echo ""
echo "    ==============================================================="
echo "    NOTE:: These both image does not have HACH propriatery recipes."
echo "    ==============================================================="
echo ""
echo "GUI DISTRO is defined in 'local.conf' file."
echo ""
echo "   * hqseries-lab-image: Full GUI/no GUI Image. That cab be x11 or xwayland or framebuffer or wayland."
echo "     ------------------"
echo ""
echo "   * hqseries-lab-image-qt: Offer Qt support. That cab be x11 or xwayland or framebuffer or wayland."
echo "     ------------------"
echo ""
echo ""

if [ $FIRST_TIME -eq 1 ]; then
	mkdir -p conf
	cp ../sources/meta-r2009-public/buildconf/*.conf conf/
fi
