#!/bin/sh
ECHO=`which echo`
BUILDDIR="/opt/hachdev/buildsystem/r2009/build"
FIRST_TIME=0
cd /opt/hachdev/buildsystem/r2009/sources/poky
if [ ! -f ${BUILDDIR}/conf/local.conf ]; then
	FIRST_TIME=1
fi

. ./oe-init-build-env ${BUILDDIR}

echo ""
echo "HACH provides the following image recipes for r2009 project:"
echo "   * fsl-image-gui: Based on Variscite fsl-image-gui"
echo ""

if [ $FIRST_TIME -eq 1 ]; then
	mkdir -p conf
	cp ../sources/meta-r2009-public/buildconf/*.conf conf/
fi
